<html>

<head>
    <title>Phriedman Systems</title>
    <link rel="stylesheet" href="main.css">
    <style>
        .bottombutton {
            padding: 18px;
            background-color: rgb(24, 73, 19);
            border-radius: 9px;
            color: #eee;
            text-decoration: none;
            font-size: large;
            font-weight: bold;
        }
        
        .bottombutton:hover {
            background-color: rgb(37, 92, 30);
        }
        
        .buttontext {
            display: inline-block;
            width: 170px;
        }
    </style>
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/" class="active">Home</a></li>
            <li class="navbar"><a href="/products.html">Products</a></li>
            <li class="navbar"><a href="/sales.html">Sales</a></li>
            <li class="navbar"><a href="/employees.html">Employees</a></li>
            <li class="navbar"><a href="/careers.html">Careers</a></li>
            <li class="navbar"><a href="/about.html">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <h2><i>&ldquo;Tomorrow's quality, in 24 hours or it's free&rdquo;</i></h2>
        <p>
            Phriedman Systems is a leading engineering products manufacturer in the DMV area. We provide critical manufacturing services for a variety of customers including the aviation, marketing, pollution and environmental management, and dairy production industries.
            We are proud to ensure 100% quality in our products, and we hope you will become one of our valued customers.
        </p>
        <img src="img/x-r34j3.jpg" alt="" width="70%">
        <div class="caption">The X-R32J3, our flagship ceilometer.</div>
        <img src="img/missile.jpg" alt="" width="70%">
        <div class="caption">One of our 7B-33 weapons platforms engaging a target.</div>
        <img src="img/cows.jpg" alt="" width="70%">
        <div class="caption">Happy and productive cows, secure under the watchful<br>eye of our atmospheric monitoring manifolds.
        </div>
        <br>
        <p>
            Interested in starting a discussion to move your business to the next level with the help of advanced, cutting-edge Phriedman technology? Reach out to us, and we would be glad to help.
        </p><br>
        <a class="bottombutton" href="/products.html">
            <span class="buttontext">View our Products</span> 🢡
        </a><br><br><br>
        <a class="bottombutton" href="/careers.html">
            <span class="buttontext">Join Our Team</span> 🢡
        </a>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html><html>

<head>
    <title>Phriedman Systems | Products</title>
    <link rel="stylesheet" href="main.css">
    <style>
        .prodname {
            font-weight: 900;
            font-size: large;
        }
    </style>
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/">Home</a></li>
            <li class="navbar"><a href="/products.html" class="active">Products</a></li>
            <li class="navbar"><a href="/sales.html">Sales</a></li>
            <li class="navbar"><a href="/employees.html">Employees</a></li>
            <li class="navbar"><a href="/careers.html">Careers</a></li>
            <li class="navbar"><a href="/about.html">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <p>
            Please enjoy your experience browsing this partial, yet comprehensive, listing of our multitude of dynamic and synergistic products.
        </p>
        <h2 style="font-variant: small-caps;">Ceilometers</h2>
        <ul>
            <li><span class="prodname">X-R32J3</span>
                <br>Our flagship unit, suitable for any usage.</li>
            <li><span class="prodname">X-R32J4</span>
                <br>Comes with extra flange.</li>
            <li><span class="prodname">X-R388U</span></li>
            <li><span class="prodname">X-R3944L</span>
                <br>Built specially for small spaces.
                <br>WARNING: Risk of combustion and asphyxiation. Please contact sales department, safety and ethics group before purchase (dial 2-3).</li>
            <li><span class="prodname">X-R3AA-53</span>
                <br>Legacy unit. Purchase not recommended.</li>
        </ul>
        <h2 style="font-variant: small-caps;">Hygrometers</h2>
        <ul>
            <li><span class="prodname">Q-L620</span>
                <br>Legacy unit. Please replace with Z-496.</li>
            <li><span class="prodname">L-77658HG3482</span>
                <br>Robust unit for installation in high-G environments.
                <br>Comes with additional computational system for GPU offloading of system atmospheric dynamics calculation matrices.</li>
            <li><span class="prodname">Z-496</span>
                <br>Standard lithium-based system. Purchase not recommended due to recall.</li>
            <li><span class="prodname">KG-WW44</span>
                <br>For installation in zero-moisture environments.</li>
        </ul>
        <h2 style="font-variant: small-caps;">Security Systems</h2>
        <ul>
            <li><span class="prodname">F-33683</span>
                <br>Basic security monitoring system for standard installation.</li>
            <li><span class="prodname">F-7744</span></li>
            <li><span class="prodname">F-05953</span></li>
            <li><span class="prodname">F-443</span>
                <br>Comes with enhanced input apparatus.</li>
            <li><span class="prodname">F-H-05644</span></li>
        </ul>
        <h2 style="font-variant: small-caps;">Missiles</h2>
        <ul>
            <li><span class="prodname">7B-33</span>
                <br>Low-cost propelled rocket system for everyday use.</li>
            <li><span class="prodname">8B-34</span>
                <br>High-impact, industry-shaking, innovative full missile solution suite.</li>
            <li><span class="prodname">7B-95</span>
                <br>Waterproof model.
                <br>BUY NOW for included T-shirt!</li>
        </ul>
        <h2 style="font-variant: small-caps;">Thermobaric Weapons Platforms</h2>
        <ul>
            <li><span class="prodname">T-99G</span>
                <br>An impressive all-in-one titan for real vacuumizing of your fuel-air mix.</li>
            <li><span class="prodname">T-991G</span></li>
            <li><span class="prodname">T-993G</span></li>
            <li><span class="prodname">T-994G</span></li>
            <li><span class="prodname">T-35L</span>
                <br>Comes with specialized targeting system.</li>
            <li><span class="prodname">T-438V</span>
                <br>Turquoise variant.</li>
            <li><span class="prodname">T-88F</span>
                <br>Includes seat.</li>
        </ul>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html><html>

<head>
    <title>Phriedman Systems | Sales</title>
    <link rel="stylesheet" href="main.css">
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/">Home</a></li>
            <li class="navbar"><a href="/products.html">Products</a></li>
            <li class="navbar"><a href="/sales.html" class="active">Sales</a></li>
            <li class="navbar"><a href="/employees.html">Employees</a></li>
            <li class="navbar"><a href="/careers.html">Careers</a></li>
            <li class="navbar"><a href="/about.html">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <p>
            Webpage is under construction!!!
        </p>
        <img src="https://content.presentermedia.com/files/animsp/00022000/22851/construction_guy_sledgehammer_rest_md_wm.gif" alt="">
        <img src="https://i.pinimg.com/originals/eb/1b/27/eb1b27863813653543914d222ceb9cd0.gif" alt="">
        <p>
            Please contact our sales team directly.
        </p>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html><html>

<head>
    <title>Phriedman Systems | Employees</title>
    <link rel="stylesheet" href="main.css">
    <style>
        .employee {
            display: flex;
            flex-direction: row;
            /*border-bottom: 1px solid white;*/
            margin-bottom: 30px;
        }
        
        .employee img {
            height: 120px;
            margin-right: 20px;
        }
        
        .employee h2 {
            margin: 10px 0;
        }
    </style>
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/">Home</a></li>
            <li class="navbar"><a href="/products.html">Products</a></li>
            <li class="navbar"><a href="/sales.html">Sales</a></li>
            <li class="navbar"><a href="/employees.html" class="active">Employees</a></li>
            <li class="navbar"><a href="/careers.html">Careers</a></li>
            <li class="navbar"><a href="/about.html">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <div class="employee">
            <img src="employees/ceo.jpg">
            <div>
                <h2>Conrad Smith - CEO</h2>
                Hi! I'm the CEO of Phriedman. I'm very proud of my company and the important work we do every day.
                <br>Office 30
            </div>
        </div>
        <div class="employee">
            <img src="employees/1.jpg">
            <div>
                <h2>Mike Ruppsen - VP of Sales</h2>
                I'm Mike. Please contact me at any time, I'd be pleased to discuss a sales agreement with you.
                <br>Office 33
            </div>
        </div>
        <div class="employee">
            <img src="employees/2.jpg">
            <div>
                <h2>Valentina A. Frudd - VP of Product Development</h2>
                Office 34
            </div>
        </div>
        <div class="employee">
            <img src="employees/3.jpg">
            <div>
                <h2>August Martey - VP of Relations</h2>
                Previously director of HR
                <br>Office 12
            </div>
        </div>
        <div class="employee">
            <img src="employees/4.jpg">
            <div>
                <h2>Loudon D. Vedley - VP of Sanitation Services</h2>
                Office 13
            </div>
        </div>
        <div class="employee">
            <img src="employees/5.jpg">
            <div>
                <h2>Stephanie Leaver - Director of HR</h2>
                Always feel free to contact me with any workplace issues.
                <br>Office 11
            </div>
        </div>
        <div class="employee">
            <img src="employees/6.jpg">
            <div>
                <h2>Jim Riddley - Senior Engineer</h2>
                Office 16
            </div>
        </div>
        <div class="employee">
            <img src="employees/7.jpg">
            <div>
                <h2>Rob Fiddson - Mechanical Engineer</h2>
                Contact me at rfiddson@phriedmansystems
                <br>Room 19
            </div>
        </div>
        <div class="employee">
            <img src="employees/8.jpg">
            <div>
                <h2>Pat Eddlin - Chemical Engineer</h2>
                Working hard to keep the ceilometers ceilometing!
                <br>Room 20
            </div>
        </div>
        <div class="employee">
            <img src="employees/9.jpg">
            <div>
                <h2>Arthur E. Heddsen - Chemist</h2>
                I can be reached at email aheddsen.
                <br>Room 20
            </div>
        </div>
        <div class="employee">
            <img src="employees/10.jpg">
            <div>
                <h2>Jim Laddlin - IT Services</h2>
                Room 09
            </div>
        </div>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html><html>

<head>
    <title>Phriedman Systems | Careers</title>
    <link rel="stylesheet" href="main.css">
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/">Home</a></li>
            <li class="navbar"><a href="/products.html">Products</a></li>
            <li class="navbar"><a href="/sales.html">Sales</a></li>
            <li class="navbar"><a href="/employees.html">Employees</a></li>
            <li class="navbar"><a href="/careers.html" class="active">Careers</a></li>
            <li class="navbar"><a href="/about.html">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <h2>
            Interested in working at Phriedman?
        </h2>
        <img src="img/shirtguy.png" width="40%" style="float: right; margin: 0px; margin-left: 20px;">
        <p>
            We'd love to have you at our company. Phriedman Systems is a dynamic workplace in the bustling exurban-adjacent, downtown-urban semi-rural center of the outskirts of Beltsville, MD. Several competitive on-site amenities are available for employees, including
            an office cafe, a gym, and a free-of-charge restroom.
        </p>
        <p>
            Here, we care about our employees, and we hope you'll join us on our mission to Empower the Power of Next-Generation Industry.
        </p>
        <p>
            We are currently hiring for <b>the following roles</b>:
        </p>
        <ul>
            <li>Senior Software Engineer</li>
            <li>Chemical Engineer</li>
            <li>System Administrator</li>
            <li>Cybersecurity Engineer</li>
            <li>Pneumatics Technician</li>
            <li>Test Pilot (Hazard pay included)</li>
            <li>Summer Piloting Intern</li>
            <li>Chief Executive Officer</li>
        </ul>
        <p>
            If you are interested in a career, please speak with our HR department by dialing 3 (three). Alternatively, email Director of HR Stephanie Leaver at sleaver@phriedman.xyz. <i>Note from IT dept: Email system is currently down for maintenance.</i>
        </p>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html><html>

<head>
    <title>Phriedman Systems | About Us</title>
    <link rel="stylesheet" href="main.css">
</head>

<body>
    <div class="content header">
        <img src="img/logo.webp" alt="" height="100px" style="margin-left: -20px">
    </div>
    <div class="navcontainer">
        <ul class="navbar">
            <li class="navbar"><a href="/">Home</a></li>
            <li class="navbar"><a href="/products.html">Products</a></li>
            <li class="navbar"><a href="/sales.html">Sales</a></li>
            <li class="navbar"><a href="/employees.html">Employees</a></li>
            <li class="navbar"><a href="/careers.html">Careers</a></li>
            <li class="navbar"><a href="/about.html" class="active">About Us</a></li>
        </ul>
    </div>
    <div class="content">
        <img src="employees/ceo.jpg" width="30%" style="float: right; margin: 0px;
            margin-left: 20px; margin-bottom: 20px;">
        <p>
            As our homepage explains, Phriedman Systems is a leading engineering products manufacturer in the DMV area. We provide critical manufacturing services for a variety of customers including the aviation, marketing, pollution and environmental management,
            and dairy production industries. We are proud to ensure 100% quality in our products.
        </p>
        <p>
            Here at Phriedman, we're deeply dedicated to what we do.
        </p>
        <i>
            "Ever since I started my first business selling computer parts in my hometown, I've been personally
            committed to quality service, professionalism, ethical business practices, and extreme mission efficacy."
        </i>
        <br>
        <p style="margin-top: 5px;">
            <b style="margin-left: 60px;">
                ~ Our CEO, Conrad Smith (pictured right)
            </b>
        </p>
        <p>
            Few know that Phriedman Systems began as a mere ceilometer manufacturer, branching off from our CEO's first business. Over time we diversified to obtain our vast portfolio of today's products and services. We moved down to the DMV in 2014 to better facilitate
            service for customers in the region. To hear all about our exciting corporate story, feel free to contact us and ask about company info.
        </p>
    </div>
    <div class="bottomsep"></div>
    <footer class="content">
        <span style="font-style: normal; font-weight: bold;">(c)</span> Phriedman Systems, Ltd. 2015-2018
        <div style="float: right; text-align: right;">
            Phone: <b>‪(301) 902-0806‬</b><br> Fax: <b>Coming Soon</b>
        </div>
        <br> 1083 Midgen Road, Beltsville MD, 20332
    </footer>
</body>

</html>